name: Check for pushes to test branch

on:
  schedule:
    - cron: "15 18 * * *"  # Runs daily at 5 AM UTC, which corresponds to midnight ET during Standard Time
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-pushes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
        
      - name: Check for pushes to the branch in the last 24 hours
        id: check_pushes
        run: |
          # Get the current time in seconds since epoch
          current_time=$(date +%s)
          # Get the commits in the last 12 hours on the branch
          commits=$(git log --since="24 hours ago" --oneline --actions-test/test)

          if [ -z "$commits" ]; then
            echo "No commits in the last 12 hours."
          else
            echo "Commits in the last 12 hours:"
            echo "$commits"
          fi
