name: Check for pushes to test branch

on:
  schedule:
    - cron: "15 18 * * *"  # Runs daily at 5 AM UTC, which corresponds to midnight ET during Standard Time
  workflow_dispatch:

jobs:
  check-pushes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:

          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for pushes to the 'test' branch in the last 24 hours
        id: check_pushes
        run: |
          # Set the branch name you want to check
          BRANCH="test"  # Change this to your target branch

          git fetch actions-test $BRANCH
          # Get the current timestamp (current time in seconds)
          CURRENT_TIMESTAMP=$(date +%s)

          # Get the timestamp of 24 hours ago
          LAST_24HRS_TIMESTAMP=$(date --date='24 hours ago' +%s)

          # Get the timestamp of the latest commit on the remote branch
          LATEST_COMMIT_TIMESTAMP=$(git log -1 --format=%ct origin/$BRANCH)

          # Compare the commit timestamp with the 24 hours ago timestamp
          if [ $LATEST_COMMIT_TIMESTAMP -ge $LAST_24HRS_TIMESTAMP ]; then
            echo "There was a commit in the last 24 hours on the remote $BRANCH branch."
          else
            echo "No commits in the last 24 hours on the remote $BRANCH branch."
            exit 1  # Optionally exit with an error if no commit found in the last 24 hours
          fi
