name: Check for pushes to test branch

on:
  schedule:
    - cron: "15 18 * * *"  # Runs daily at 5 AM UTC, which corresponds to midnight ET during Standard Time
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-pushes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check for pushes to the 'test' branch in the last 24 hours
        id: check_pushes
        run: |
          # Set the branch name you want to check
          BRANCH="main"  # Change this to your target branch

          # Get the latest commit date for the test branch
          LAST_COMMIT_DATE=$(git log -1 --since="1 day ago" --format=%cd --date=iso8601)
          if [[ -n "$LAST_COMMIT_DATE" && $(git branch --show-current) == "test" ]]; then
            echo "Pushes detected on 'test' branch in the last 24 hours"
            chmod +x build_run.sh
            ./build_run.sh
          else
            echo "No pushes to the 'test' branch in the last 24 hours"
          fi
