name: Multiple Steps
on:
  push:
    branches:
      - main
    
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Make
        run: sudo apt-get install make

      - name: Build Code
        run: make sample_prog
      
      - name: Move to build folder
        run: | 
          mkdir build
          mv *.o build
          mv sample_prog build

      - name: Upload build folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/

  test:
    runs-on: ubuntu-latest
    needs: build  # This makes the 'package' job dependent on 'build' job
    steps:
      # Checkout code again (for the context of the repository)
      - name: Checkout code
        uses: actions/checkout@v4

      # Download the artifact from the 'build' job
      # - name: Download build artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: build-artifact

      - name: Run test
        run: |
          ls -a
          cd build
          ./sample_prog
