name: Testing Containerized run

on:

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sujitlak/docker-repos:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4

      - name: Display cwd
        run: |
        pwd
        ls

      - name: Build program
        run: make

      - name: Run Program on Docker
        run: ./hello_world
