name: Testing Containerized run

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sujitlak/docker-repos:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
      volumes:
       - basic-program:/apps

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display cwd
        run: |
          ls /apps

      - name: Build program
        run: /apps/make

      - name: Run Program on Docker
        run: ./hello_world
