name: Testing Containerized run

on:

  workflow_dispatch:

jobs:

  pull-container:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/sujitlak/docker-repos:main   

  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sujitlak/docker-repos:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build program
        run: make

      - name: Run Program on Docker
        run: ./hello_world